### ISSUE TITLE
npm install returns a 404

### ISSUE THREAD

**Issue by dannybloe** [walkerrandolphsmith/react-loupe#2]
When I try to install this package using `npm install @walkerandolphsmith/react-loupe` or `npm install react-loupe` it returns a 404. Is the package correctly registered?

**Comment by walkerrandolphsmith** [comment]
I will look into this and get back to you.

**Comment by walkerrandolphsmith** [comment]
@nicholas-b-carter  I notice you published to npm with the new name. The module on npm is no longer scoped. Do you have any idea why the scoped package was receiving a 404. Also I am not able to publish updates the the non-scoped package given I didn't publish it. Do you know how to add me as a contributor to the package on npmorg?

**Comment by nicholas-b-carter** [comment]
@walkerrandolphsmith https://docs.npmjs.com/getting-started/scoped-packages#publishing-a-scoped-package. I can remove the package from the registry. You would need to re-publish the scoped package with the `npm publish --access=public` tags when publishing. Although I thought I tried this and still wasn't able to publish it.... I read another article where they stated that as of like  October they were no longer supporting public spoked packages....

**Comment by nicholas-b-carter** [comment]
@walkerrandolphsmith https://docs.npmjs.com/misc/scope
